"use client";

import { useState } from "react";
import { Bell, Building2, Check, KeyRound, Link2, LockKeyhole, MonitorCog, Palette, Save, Shield, UserRound, UsersRound } from "lucide-react";
import { Modal, PageHeader, StatusBadge, Toast } from "@/components/ui";

const sections = [
  { name: "Profile", icon: UserRound }, { name: "Laboratory", icon: Building2 }, { name: "Appearance", icon: Palette },
  { name: "Notifications", icon: Bell }, { name: "User Roles", icon: UsersRound }, { name: "Security", icon: Shield }, { name: "Integrations", icon: Link2 },
];

function Toggle({ value, onChange, label }: { value: boolean; onChange: () => void; label: string }) {
  return <button className={`switch ${value ? "on" : ""}`} onClick={onChange} role="switch" aria-checked={value} aria-label={label} />;
}

export default function SettingsPage() {
  const [section, setSection] = useState("Profile");
  const [dark, setDark] = useState(false);
  const [emailNotices, setEmailNotices] = useState(true);
  const [criticalNotices, setCriticalNotices] = useState(true);
  const [taskNotices, setTaskNotices] = useState(true);
  const [securityOpen, setSecurityOpen] = useState(false);
  const [toast, setToast] = useState(false);
  const save = () => { setToast(true); window.setTimeout(() => setToast(false), 2000); };
  const changeTheme = (nextDark: boolean) => { setDark(nextDark); document.documentElement.dataset.theme = nextDark ? "dark" : "light"; localStorage.setItem("helix-theme", nextDark ? "dark" : "light"); };
  return (
    <div className="page">
      <PageHeader eyebrow="Workspace configuration" title="Settings" description="Manage your profile, laboratory preferences, security, and connected tools." actions={<button className="btn btn-primary" onClick={save}><Save/> Save changes</button>} />
      <section className="setting-layout">
        <aside className="card" style={{ padding: 10, alignSelf: "start" }}><nav className="setting-nav" aria-label="Settings sections">{sections.map((item) => <button key={item.name} className={section === item.name ? "active" : ""} onClick={() => setSection(item.name)}><item.icon size={17}/>{item.name}</button>)}</nav></aside>
        <div className="card"><div className="card-header"><div><h2>{section}</h2><p>Mock configuration for Molecular Biotechnology Lab</p></div></div><div className="card-body">
          {section === "Profile" && <div className="form-grid"><div className="span-2" style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 4 }}><div className="avatar" style={{ width: 64, height: 64, fontSize: 18 }}>DK</div><div><strong>Dr. Kan</strong><div className="cell-sub">Biotechnology Researcher</div><button className="btn btn-secondary btn-sm" style={{ marginTop: 7 }} onClick={save}>Change photo</button></div></div><div className="field"><label htmlFor="first-name">First name</label><input id="first-name" className="input" defaultValue="Kan"/></div><div className="field"><label htmlFor="last-name">Display title</label><input id="last-name" className="input" defaultValue="Dr. Kan"/></div><div className="field"><label htmlFor="profile-email">Email</label><input id="profile-email" className="input" defaultValue="dr.kan@helixlab.io" type="email"/></div><div className="field"><label htmlFor="profile-position">Position</label><input id="profile-position" className="input" defaultValue="Biotechnology Researcher"/></div><div className="field span-2"><label htmlFor="profile-bio">Research focus</label><textarea id="profile-bio" className="textarea" defaultValue="CRISPR validation, molecular assay development, and biotechnology workflow optimization."/></div></div>}
          {section === "Laboratory" && <div className="form-grid"><div className="field span-2"><label htmlFor="lab-name">Laboratory name</label><input id="lab-name" className="input" defaultValue="Molecular Biotechnology Lab"/></div><div className="field"><label htmlFor="lab-code">Laboratory code</label><input id="lab-code" className="input" defaultValue="MBL-BKK-01"/></div><div className="field"><label htmlFor="lab-timezone">Timezone</label><select id="lab-timezone" className="select"><option>Asia/Bangkok (UTC+7)</option><option>UTC</option></select></div><div className="field span-2"><label htmlFor="lab-address">Facility address</label><textarea id="lab-address" className="textarea" defaultValue="Biotechnology Research Center, Bangkok, Thailand"/></div><div className="field"><label htmlFor="lab-manager">Lab manager</label><input id="lab-manager" className="input" defaultValue="Dr. Anong P."/></div><div className="field"><label htmlFor="lab-contact">Emergency contact</label><input id="lab-contact" className="input" defaultValue="+66 2 555 0142"/></div></div>}
          {section === "Appearance" && <><div className="setting-row"><div><strong>Color theme</strong><p>Choose how Helix Lab appears on this device.</p></div><div className="segmented"><button className={!dark ? "active" : ""} onClick={() => changeTheme(false)}>Light</button><button className={dark ? "active" : ""} onClick={() => changeTheme(true)}>Dark</button></div></div><div className="setting-row"><div><strong>Interface density</strong><p>Comfortable spacing is optimized for mixed data and forms.</p></div><select className="select" style={{ width: 150 }}><option>Comfortable</option><option>Compact</option></select></div><div className="setting-row"><div><strong>Chart motion</strong><p>Use subtle animation when visualizations load.</p></div><Toggle value={true} onChange={save} label="Chart motion"/></div></>}
          {section === "Notifications" && <><div className="setting-row"><div><strong>Email notifications</strong><p>Receive daily summaries and direct mentions.</p></div><Toggle value={emailNotices} onChange={() => setEmailNotices(!emailNotices)} label="Email notifications"/></div><div className="setting-row"><div><strong>Critical laboratory alerts</strong><p>Temperature, contamination, and equipment safety events.</p></div><Toggle value={criticalNotices} onChange={() => setCriticalNotices(!criticalNotices)} label="Critical alerts"/></div><div className="setting-row"><div><strong>Task reminders</strong><p>Due-soon and overdue task notifications.</p></div><Toggle value={taskNotices} onChange={() => setTaskNotices(!taskNotices)} label="Task reminders"/></div><div className="setting-row"><div><strong>Quiet hours</strong><p>Non-critical messages are held during this window.</p></div><div style={{ display: "flex", gap: 7 }}><input className="input" type="time" defaultValue="20:00" style={{ width: 110 }}/><input className="input" type="time" defaultValue="07:00" style={{ width: 110 }}/></div></div></>}
          {section === "User Roles" && <div className="table-wrap"><table className="data-table"><thead><tr><th>Role</th><th>Members</th><th>Scope</th><th>Status</th></tr></thead><tbody><tr><td><strong>Lab Manager</strong></td><td>2</td><td>Full workspace administration</td><td><StatusBadge status="Available"/></td></tr><tr><td><strong>Researcher</strong></td><td>8</td><td>Create and manage assigned scientific work</td><td><StatusBadge status="Available"/></td></tr><tr><td><strong>Technician</strong></td><td>5</td><td>Samples, instruments, and task execution</td><td><StatusBadge status="Available"/></td></tr><tr><td><strong>Viewer</strong></td><td>3</td><td>Read-only access to approved records</td><td><StatusBadge status="Available"/></td></tr></tbody></table><div className="alert alert-info" style={{ marginTop: 16 }}><LockKeyhole/><div><strong>UI preview only</strong><p>Role changes do not grant real permissions until backend authorization is connected.</p></div></div></div>}
          {section === "Security" && <><div className="setting-row"><div><strong>Password</strong><p>Last changed 42 days ago.</p></div><button className="btn btn-secondary" onClick={() => setSecurityOpen(true)}><KeyRound/> Change password</button></div><div className="setting-row"><div><strong>Two-factor authentication</strong><p>Add an authenticator app for stronger account security.</p></div><button className="btn btn-secondary" onClick={save}>Set up</button></div><div className="setting-row"><div><strong>Active sessions</strong><p>3 signed-in devices, including this browser.</p></div><button className="btn btn-secondary" onClick={() => setSecurityOpen(true)}><MonitorCog/> Review</button></div></>}
          {section === "Integrations" && <div className="grid-2">{[{ name: "Laboratory instruments", copy: "Connect sequencers and instrument data sources", connected: false },{ name: "Cloud file storage", copy: "Reference analysis files and attachments", connected: true },{ name: "Identity provider", copy: "Enterprise SSO and directory sync", connected: false },{ name: "Notification channels", copy: "Send operational alerts to team channels", connected: true }].map((item) => <div className="card stat-card" key={item.name}><div className="stat-icon"><Link2/></div><div className="list-copy"><strong style={{ fontSize: 14 }}>{item.name}</strong><span>{item.copy}</span></div><button className="btn btn-secondary btn-sm" onClick={save}>{item.connected ? "Manage" : "Connect"}</button></div>)}</div>}
        </div><footer className="card-footer" style={{ display: "flex", justifyContent: "flex-end", gap: 9 }}><button className="btn btn-secondary" onClick={() => setSection("Profile")}>Discard</button><button className="btn btn-primary" onClick={save}><Check/> Save {section.toLowerCase()}</button></footer></div>
      </section>
      <Modal open={securityOpen} onClose={() => setSecurityOpen(false)} title="Security check" description="This frontend demonstrates the flow without changing authentication data." footer={<><button className="btn btn-secondary" onClick={() => setSecurityOpen(false)}>Cancel</button><button className="btn btn-primary" onClick={() => { setSecurityOpen(false); save(); }}>Confirm</button></>}><div className="form-grid"><div className="field span-2"><label htmlFor="current-password">Current password</label><input id="current-password" className="input" type="password" placeholder="••••••••"/></div><div className="field"><label htmlFor="new-password">New password</label><input id="new-password" className="input" type="password" placeholder="Minimum 12 characters"/></div><div className="field"><label htmlFor="confirm-password">Confirm password</label><input id="confirm-password" className="input" type="password" placeholder="Repeat new password"/></div></div></Modal>
      <Toast show={toast} title="Settings saved" description="Preferences were updated for this frontend session."/>
    </div>
  );
}
