from datetime import datetime
from html import escape
from io import BytesIO
import os
from pathlib import Path
import re
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


MIME_TYPES = {
    "pdf": "application/pdf",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
}

LABELS = {
    "en": {
        "experiment_summary": "Experiment Summary",
        "sample_inventory": "Sample Inventory",
        "quality_control": "Quality Control",
        "generated": "Generated",
        "generated_by": "Generated by",
        "experiment": "Experiment",
        "status": "Status",
        "priority": "Priority",
        "objective": "Objective",
        "protocol": "Protocol",
        "samples": "Samples",
        "lab_notes": "Lab Notes",
        "ai_summary": "AI-assisted Summary",
        "exceptions": "Administrative Quality Exceptions",
        "disclaimer": "Decision-support document. Verify all conclusions against source records and approved protocols.",
        "qc_disclaimer": "This section checks record completeness and workflow status; it is not a validated assay-quality result.",
    },
    "th": {
        "experiment_summary": "สรุปการทดลอง",
        "sample_inventory": "รายงานคลังตัวอย่าง",
        "quality_control": "รายงานควบคุมคุณภาพ",
        "generated": "สร้างเมื่อ",
        "generated_by": "สร้างโดย",
        "experiment": "การทดลอง",
        "status": "สถานะ",
        "priority": "ความสำคัญ",
        "objective": "วัตถุประสงค์",
        "protocol": "โพรโทคอล",
        "samples": "ตัวอย่าง",
        "lab_notes": "บันทึกห้องปฏิบัติการ",
        "ai_summary": "สรุปโดย AI",
        "exceptions": "ข้อยกเว้นด้านข้อมูลและขั้นตอนงาน",
        "disclaimer": "เอกสารนี้ใช้เพื่อช่วยตัดสินใจ โปรดตรวจสอบข้อสรุปกับข้อมูลต้นทางและโพรโทคอลที่ได้รับอนุมัติ",
        "qc_disclaimer": "ส่วนนี้ตรวจความครบถ้วนของข้อมูลและสถานะกระบวนการ ไม่ใช่ผลรับรองคุณภาพของการทดสอบ",
    },
}


def _font_paths() -> tuple[str | None, str | None]:
    candidates = [
        (
            "/usr/share/fonts/truetype/noto/NotoSansThai-Regular.ttf",
            "/usr/share/fonts/truetype/noto/NotoSansThai-Bold.ttf",
        ),
        (
            "C:/Windows/Fonts/NotoSansThai-Regular.ttf",
            "C:/Windows/Fonts/NotoSansThai-Bold.ttf",
        ),
    ]
    custom_regular = os.getenv("REPORT_FONT_REGULAR")
    custom_bold = os.getenv("REPORT_FONT_BOLD")
    if custom_regular:
        candidates.insert(0, (custom_regular, custom_bold or custom_regular))
    for regular, bold in candidates:
        if Path(regular).exists() and Path(bold).exists():
            return regular, bold
    return None, None


def _register_fonts() -> tuple[str, str]:
    regular, bold = _font_paths()
    if regular and bold:
        if "HelixSans" not in pdfmetrics.getRegisteredFontNames():
            pdfmetrics.registerFont(TTFont("HelixSans", regular))
            pdfmetrics.registerFont(TTFont("HelixSans-Bold", bold))
        return "HelixSans", "HelixSans-Bold"
    return "Helvetica", "Helvetica-Bold"


def report_filename(report: dict[str, Any]) -> str:
    slug = re.sub(r"[^A-Za-z0-9-]+", "-", report["title"]).strip("-").lower() or "report"
    return f"helix-{report['id'].lower()}-{slug[:60]}.{report['format']}"


def _paragraph(value: Any, style: ParagraphStyle) -> Paragraph:
    text = "—" if value is None or value == "" else str(value)
    return Paragraph(escape(text).replace("\n", "<br/>"), style)


def _person_name(value: Any) -> str:
    if isinstance(value, dict):
        return str(value.get("display_name") or value.get("username") or "")
    return str(value or "")


def build_pdf(report: dict[str, Any]) -> bytes:
    snapshot = report["snapshot"]
    language = report.get("language", "en")
    labels = LABELS[language]
    regular_font, bold_font = _register_fonts()
    styles = getSampleStyleSheet()
    body = ParagraphStyle("HelixBody", parent=styles["BodyText"], fontName=regular_font, fontSize=9, leading=13, wordWrap="CJK", textColor=colors.HexColor("#27272a"))
    small = ParagraphStyle("HelixSmall", parent=body, fontSize=7.5, leading=10, textColor=colors.HexColor("#71717a"))
    heading = ParagraphStyle("HelixHeading", parent=styles["Heading2"], fontName=bold_font, fontSize=14, leading=18, spaceBefore=10, spaceAfter=7, textColor=colors.HexColor("#134e4a"), wordWrap="CJK")
    title_style = ParagraphStyle("HelixTitle", parent=heading, fontSize=21, leading=25, alignment=TA_CENTER, spaceAfter=5)
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=18 * mm, leftMargin=18 * mm, topMargin=18 * mm, bottomMargin=18 * mm, title=report["title"], author="Helix Lab")
    story: list[Any] = [
        Paragraph("HELIX LAB · LABORATORY OS", ParagraphStyle("Brand", parent=small, alignment=TA_CENTER, fontName=bold_font, textColor=colors.HexColor("#0f766e"))),
        Spacer(1, 4 * mm),
        _paragraph(report["title"], title_style),
        _paragraph(labels[report["report_type"]], ParagraphStyle("Type", parent=body, alignment=TA_CENTER, textColor=colors.HexColor("#71717a"))),
        Spacer(1, 7 * mm),
    ]
    meta = [
        [labels["generated"], snapshot["generated_at"]],
        [labels["generated_by"], snapshot["generated_by"]],
        ["Report ID", report["id"]],
    ]
    meta_table = Table([[_paragraph(a, small), _paragraph(b, body)] for a, b in meta], colWidths=[38 * mm, 120 * mm])
    meta_table.setStyle(TableStyle([("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f4f4f5")), ("GRID", (0, 0), (-1, -1), .35, colors.HexColor("#d4d4d8")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 7), ("RIGHTPADDING", (0, 0), (-1, -1), 7), ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5)]))
    story.extend([meta_table, Spacer(1, 5 * mm)])

    experiment = snapshot.get("experiment")
    if experiment:
        story.append(_paragraph(labels["experiment"], heading))
        rows = [
            ["ID", experiment.get("id")],
            [labels["experiment"], experiment.get("title")],
            [labels["status"], experiment.get("status")],
            [labels["priority"], experiment.get("priority")],
            [labels["objective"], experiment.get("objective")],
            [labels["protocol"], experiment.get("protocol")],
        ]
        table = Table([[_paragraph(a, small), _paragraph(b, body)] for a, b in rows], colWidths=[38 * mm, 120 * mm], repeatRows=0)
        table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), .35, colors.HexColor("#d4d4d8")), ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f4f4f5")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 6), ("RIGHTPADDING", (0, 0), (-1, -1), 6), ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5)]))
        story.append(table)

    samples = snapshot.get("samples", [])
    if samples:
        story.append(_paragraph(labels["samples"], heading))
        rows = [["ID", "Name", "Type", "Status", "Location", "Temperature"]]
        rows.extend([[item.get("id"), item.get("name"), item.get("type"), item.get("status"), item.get("location"), item.get("temperature")] for item in samples])
        table = Table([[_paragraph(cell, small if row_index == 0 else body) for cell in row] for row_index, row in enumerate(rows)], colWidths=[24 * mm, 36 * mm, 25 * mm, 21 * mm, 35 * mm, 20 * mm], repeatRows=1)
        table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#ccfbf1")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#134e4a")), ("GRID", (0, 0), (-1, -1), .3, colors.HexColor("#d4d4d8")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4), ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4)]))
        story.append(table)

    notes = snapshot.get("lab_notes", [])
    if notes:
        story.append(_paragraph(labels["lab_notes"], heading))
        for note in notes:
            story.extend([_paragraph(f"{note.get('id')} · {note.get('title')}", ParagraphStyle("NoteTitle", parent=body, fontName=bold_font)), _paragraph(note.get("content"), body), Spacer(1, 2 * mm)])

    exceptions = snapshot.get("quality_exceptions", [])
    if report["report_type"] == "quality_control":
        story.append(_paragraph(labels["exceptions"], heading))
        story.append(_paragraph(labels["qc_disclaimer"], small))
        story.append(Spacer(1, 2 * mm))
        if exceptions:
            for item in exceptions:
                story.append(_paragraph(f"• {item}", body))
        else:
            story.append(_paragraph("No administrative exceptions detected." if language == "en" else "ไม่พบข้อยกเว้นด้านข้อมูลหรือสถานะ", body))

    if report.get("ai_summary"):
        story.append(_paragraph(labels["ai_summary"], heading))
        story.append(_paragraph(report["ai_summary"], body))

    story.extend([Spacer(1, 7 * mm), _paragraph(labels["disclaimer"], small)])

    def footer(canvas: Any, document: Any) -> None:
        canvas.saveState()
        canvas.setFont(regular_font, 7)
        canvas.setFillColor(colors.HexColor("#71717a"))
        canvas.drawString(18 * mm, 10 * mm, f"Helix Lab · {report['id']}")
        canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {document.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return buffer.getvalue()


def build_xlsx(report: dict[str, Any]) -> bytes:
    snapshot = report["snapshot"]
    labels = LABELS[report.get("language", "en")]
    workbook = Workbook()
    summary = workbook.active
    summary.title = "Summary"
    teal_fill = PatternFill("solid", fgColor="0F766E")
    pale_fill = PatternFill("solid", fgColor="CCFBF1")
    white_bold = Font(color="FFFFFF", bold=True)
    bold = Font(bold=True)
    summary.append(["Helix Lab", labels[report["report_type"]]])
    summary.append(["Report ID", report["id"]])
    summary.append([labels["generated"], snapshot["generated_at"]])
    summary.append([labels["generated_by"], snapshot["generated_by"]])
    summary.append(["Language", report["language"]])
    summary.append([])
    summary.append([labels["ai_summary"], report.get("ai_summary") or "Not included"])
    summary.append([])
    summary.append(["Disclaimer", labels["disclaimer"]])
    summary["A1"].fill = teal_fill
    summary["A1"].font = white_bold
    summary["B1"].fill = teal_fill
    summary["B1"].font = white_bold

    experiment = snapshot.get("experiment")
    if experiment:
        sheet = workbook.create_sheet("Experiment")
        sheet.append(["Field", "Value"])
        for key in ["id", "title", "status", "priority", "objective", "protocol", "method_notes", "start_date", "due_date"]:
            sheet.append([key.replace("_", " ").title(), experiment.get(key)])

    samples_sheet = workbook.create_sheet("Samples")
    sample_headers = ["ID", "Name", "Type", "Status", "Owner", "Collection Date", "Location", "Temperature", "Intake Note"]
    samples_sheet.append(sample_headers)
    for item in snapshot.get("samples", []):
        samples_sheet.append([item.get("id"), item.get("name"), item.get("type"), item.get("status"), _person_name(item.get("owner")), item.get("collection_date"), item.get("location"), item.get("temperature"), item.get("intake_note")])

    notes_sheet = workbook.create_sheet("Lab Notes")
    notes_sheet.append(["ID", "Title", "State", "Author", "Updated", "Content"])
    for item in snapshot.get("lab_notes", []):
        notes_sheet.append([item.get("id"), item.get("title"), item.get("state"), _person_name(item.get("author")), item.get("updated_at"), item.get("content")])

    exceptions_sheet = workbook.create_sheet("Quality Exceptions")
    exceptions_sheet.append([labels["exceptions"]])
    exceptions_sheet.append([labels["qc_disclaimer"]])
    for item in snapshot.get("quality_exceptions", []):
        exceptions_sheet.append([item])

    ai_sheet = workbook.create_sheet("AI Summary")
    ai_sheet.append([labels["ai_summary"]])
    ai_sheet.append([report.get("ai_summary") or "Not included"])
    ai_sheet.append([])
    ai_sheet.append([labels["disclaimer"]])

    for sheet in workbook.worksheets:
        sheet.freeze_panes = "A2"
        for cell in sheet[1]:
            cell.fill = teal_fill
            cell.font = white_bold
        for row in sheet.iter_rows():
            for cell in row:
                cell.alignment = Alignment(vertical="top", wrap_text=True)
        for column_cells in sheet.columns:
            width = min(55, max(12, max(len(str(cell.value or "")) for cell in column_cells) + 2))
            sheet.column_dimensions[get_column_letter(column_cells[0].column)].width = width
        if sheet.max_row > 1:
            for cell in sheet[2]:
                if sheet.title in {"Quality Exceptions", "AI Summary"}:
                    cell.fill = pale_fill
        if sheet.title == "Summary":
            for row in range(2, sheet.max_row + 1):
                sheet.cell(row, 1).font = bold

    buffer = BytesIO()
    workbook.save(buffer)
    workbook.close()
    return buffer.getvalue()


def build_report_file(report: dict[str, Any]) -> tuple[bytes, str, str]:
    data = build_pdf(report) if report["format"] == "pdf" else build_xlsx(report)
    return data, MIME_TYPES[report["format"]], report_filename(report)
