"use client";

import { useState } from "react";
import { AlertTriangle, BarChart3, CheckCircle2, Download, FileCheck2, FileSpreadsheet, FileText, LoaderCircle, Plus, RefreshCcw, Sparkles } from "lucide-react";
import { experiments, reports, samples } from "@/data/mock";
import { Badge, PageHeader, StatCard, StatusBadge, Toast } from "@/components/ui";

export default function ReportsPage() {
  const [state, setState] = useState<"idle" | "generating" | "completed" | "failed">("idle");
  const [format, setFormat] = useState("PDF");
  const [includeAi, setIncludeAi] = useState(true);
  const [toast, setToast] = useState(false);
  const generate = (fail = false) => {
    setState("generating");
    window.setTimeout(() => setState(fail ? "failed" : "completed"), 1100);
  };
  const download = (label: string) => { void label; setToast(true); window.setTimeout(() => setToast(false), 2000); };
  return (
    <div className="page">
      <PageHeader eyebrow="Scientific communication" title="Report center" description="Build consistent experiment and inventory reports from reusable templates." actions={<><button className="btn btn-secondary" onClick={() => generate(true)}><AlertTriangle /> Demo failure</button><button className="btn btn-primary" onClick={() => generate()}><Plus /> Generate report</button></>} />
      <section className="stat-grid"><StatCard icon={<FileCheck2 />} value="24" label="Reports this month" trend="+6 from June"/><StatCard icon={<FileText />} value="18" label="PDF reports" trend="75% of output"/><StatCard icon={<FileSpreadsheet />} value="6" label="Excel exports" trend="Data focused"/><StatCard icon={<Sparkles />} value="14" label="With AI summary" trend="58% adoption"/></section>
      <section className="card section-gap"><div className="card-header"><div><h2>Report templates</h2><p>Start from a consistent laboratory format</p></div></div><div className="card-body"><div className="grid-3" style={{ margin: 0 }}>{[{ title: "Experiment summary", copy: "Objective, methods, results, and conclusions", icon: FlaskIcon },{ title: "Sample inventory", copy: "Status, custody, locations, and conditions", icon: FileSpreadsheet },{ title: "Quality control", copy: "Exceptions, thresholds, and corrective actions", icon: BarChart3 }].map(({ title, copy, icon: Icon }) => <button className="card stat-card" key={title} style={{ textAlign: "left", cursor: "pointer" }} onClick={() => generate()}><div className="stat-icon"><Icon /></div><div><strong style={{ fontSize: 15 }}>{title}</strong><span>{copy}</span></div></button>)}</div></div></section>
      <section className="grid-main">
        <div className="card"><div className="card-header"><div><h2>Generate a report</h2><p>Configure scope and output</p></div><Badge tone={state === "completed" ? "success" : state === "failed" ? "danger" : state === "generating" ? "warning" : "neutral"}>{state === "idle" ? "Ready" : state}</Badge></div><div className="card-body">
          {state === "failed" && <div className="alert alert-danger section-gap"><AlertTriangle /><div><strong>Report generation failed</strong><p>The selected experiment contains a missing result section. Update the scope or retry.</p><button className="btn btn-secondary btn-sm" style={{ marginTop: 8 }} onClick={() => generate()}><RefreshCcw /> Retry</button></div></div>}
          {state === "completed" && <div className="alert" style={{ color: "var(--success)", borderColor: "color-mix(in srgb,var(--success) 30%,transparent)", background: "var(--success-soft)", marginBottom: 16 }}><CheckCircle2 /><div><strong>Report completed</strong><p>CRISPR Validation Summary is ready in {format} format.</p></div></div>}
          <div className="form-grid"><div className="field"><label htmlFor="report-type">Report type</label><select id="report-type" className="select"><option>Experiment Summary</option><option>Results Report</option><option>Sample Inventory</option><option>Quality Control</option></select></div><div className="field"><label htmlFor="report-format">Output format</label><select id="report-format" className="select" value={format} onChange={(event) => setFormat(event.target.value)}><option>PDF</option><option>Excel</option></select></div><div className="field span-2"><label htmlFor="report-experiment">Experiment</label><select id="report-experiment" className="select">{experiments.map((item) => <option key={item.id}>{item.title}</option>)}</select></div><div className="field span-2"><label htmlFor="report-samples">Samples</label><select id="report-samples" className="select" multiple style={{ height: 96 }} defaultValue={[samples[0].id, samples[1].id]}>{samples.slice(0,8).map((item) => <option key={item.id} value={item.id}>{item.id} · {item.name}</option>)}</select></div><div className="field"><label htmlFor="range-start">From</label><input id="range-start" className="input" type="date" defaultValue="2026-07-01"/></div><div className="field"><label htmlFor="range-end">To</label><input id="range-end" className="input" type="date" defaultValue="2026-07-18"/></div><label className="check-row span-2"><input type="checkbox" checked={includeAi} onChange={(event) => setIncludeAi(event.target.checked)}/> Include AI-assisted summary and key findings</label></div>
          <div style={{ display: "flex", gap: 9, marginTop: 18 }}><button className="btn btn-primary" onClick={() => generate()} disabled={state === "generating"}>{state === "generating" ? <><LoaderCircle className="spin"/> Generating…</> : <>Generate report</>}</button><button className="btn btn-secondary" onClick={() => setState("idle")}>Reset</button></div>
        </div></div>
        <div className="report-preview"><div className="report-preview-head"><div><strong style={{ fontSize: 20 }}>Helix Lab</strong><div>Experiment Summary</div></div><div style={{ textAlign: "right" }}><strong>RPT-DRAFT</strong><div>July 18, 2026</div></div></div><h2>CRISPR Gene Editing Validation</h2><p><strong>Principal researcher:</strong> Dr. Kan</p><p><strong>Laboratory:</strong> Molecular Biotechnology Lab</p><h3 style={{ marginTop: 24 }}>Executive summary</h3><p>Guide RNA candidate B achieved the primary editing efficiency target while maintaining acceptable cell viability across technical replicates.</p><h3>Key results</h3><table><thead><tr><th>Condition</th><th>Efficiency</th><th>Viability</th></tr></thead><tbody><tr><td>Guide A</td><td>58%</td><td>92%</td></tr><tr><td>Guide B</td><td>71%</td><td>89%</td></tr><tr><td>Control</td><td>1.2%</td><td>96%</td></tr></tbody></table>{includeAi && <><h3 style={{ marginTop: 20 }}>AI-assisted summary</h3><p>Guide B is the strongest candidate. One confirmatory replicate is recommended before off-target validation.</p></>}<div style={{ display: "flex", gap: 8, marginTop: 24 }}><button className="btn btn-secondary btn-sm" onClick={() => download("PDF")}><FileText /> PDF</button><button className="btn btn-secondary btn-sm" onClick={() => download("Excel")}><FileSpreadsheet /> Excel</button><button className="btn btn-primary btn-sm" onClick={() => download("Download")} disabled={state !== "completed"}><Download /> Download</button></div></div>
      </section>
      <section className="card"><div className="card-header"><div><h2>Report history</h2><p>Previously generated outputs</p></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Report</th><th>Type</th><th>Experiment</th><th>Generated</th><th>Status</th><th>Format</th><th>Action</th></tr></thead><tbody>{reports.map((report) => <tr key={report.id}><td><div className="cell-main">{report.title}</div><div className="cell-sub">{report.id}</div></td><td>{report.type}</td><td>{report.experiment}</td><td>{report.generated}</td><td><StatusBadge status={report.status}/></td><td>{report.format}</td><td><button className="btn btn-ghost btn-icon" disabled={report.status !== "Completed"} onClick={() => download(report.format)} aria-label={`Download ${report.title}`}><Download /></button></td></tr>)}</tbody></table></div></section>
      <Toast show={toast} title="Download simulated" description="File export will be connected to the reporting service in a later phase."/>
    </div>
  );
}

function FlaskIcon() { return <BarChart3/>; }
